### ISSUE TITLE
Falsch deklarierte Sprache (AX)

### ISSUE THREAD

**Issue by Tamara240** [DP-3T/dp3t-ux-screenflows-ch#13]
Screen: Impressum

Severity: 2

Die Sprache im Screen "Impressum" ist als Englisch definiert. Der Screenreader liest damit den deutschen Text mit englischer Aussprache vor was kaum verständlich ist.

![IMG_1270](https://user-images.githubusercontent.com/65170302/84148106-c6f7d580-aa5e-11ea-98d9-b12d8bbeef78.PNG)

**Comment by bastianmorath** [comment]
Kann mit der momentanen Version nicht reproduziert werden, d.h. das Impressum wird korrekt auf Deutsch vorgelesen.
