### ISSUE TITLE
Orientierung (AX)

### ISSUE THREAD

**Issue by Tamara240** [DP-3T/dp3t-ux-screenflows-ch#15]
Screen: Wichtiger Hinweis / Covidcode eingeben

Severity: 1 (Critical)

Klickt der Screenreader-Benutzer im Screen "Covidcode eingeben" auf den Zurück-Button, wird der Fokus im Screen "Wichtiger Hinweis" auf Abbrechen "gesetzt". Der Benutzer weiss somit nicht, ob er nun in einem neuen Screen ist.

![IMG_1267](https://user-images.githubusercontent.com/65170302/84148560-7a60ca00-aa5f-11ea-9649-ec189f46d0f8.PNG)
![IMG_1268](https://user-images.githubusercontent.com/65170302/84148568-7e8ce780-aa5f-11ea-9c4c-03617286fcb0.PNG)

**Comment by bastianmorath** [comment]
Danke für die Info, das wurde mittlerweile angepasst.
