### ISSUE TITLE
Orientierung (AX)

### ISSUE THREAD

**Issue by Tamara240** [DP-3T/dp3t-ux-screenflows-ch#16]
Screen: Wichtiger Hinweis

Severity: 1 (Critical) 

Ein Screenreader-Benutzer findet nur umständlich zum Button "Abbrechen". Der Fokus beginnt in der Mitte des Screens beim Titel und führt anschliessend zum Button "Verstanden" und bleibt dort stehen. Der Benutzer hat bis jetzt noch keine Info erhalten, dass er auch die Wahl zum Abbrechen hat.

![IMG_1267](https://user-images.githubusercontent.com/65170302/84148741-b1cf7680-aa5f-11ea-8732-e46695bd1e52.PNG)

**Comment by bastianmorath** [comment]
Da der User primär den Code eingeben will, wollen wir den Fokus auf den Hinweis setzen, bevor der User auf den eigentlichen "Code eingeben" Screen kommt. Will der User aber danach wieder zurück auf den Homescreen, wird der Fokus richtigerweise auf den "Abbrechen" Button gesetzt.
