### ISSUE TITLE
App wird unbedienbar (AX)

### ISSUE THREAD

**Issue by Tamara240** [DP-3T/dp3t-ux-screenflows-ch#17]
Screen: Nach "Zurück-Button" zum Homescreen

Severity: 0 (Blocker)

Klickt ein Screenreader-Benutzer auf einen "Zurück-Button" um auf den Home-Screen zu gelangen kann eine Endlosschleife entstehen wenn dieser swiped (Streich-Geste mit dem Finger auf dem Bildschirm) bevor der Titel vorgelesen wird. Wird das gemacht, bleibt der Fokus ständig auf dem Button "SwissCovid zurück-Taste" hängen und liest diesen bei jedem Swipen wieder vor.

**Comment by bastianmorath** [comment]
Kann mit der aktuellsten Version nicht reproduziert werden. Falls das Problem weiter auftritt, bitte ein neues Issue eröffnen.
