### ISSUE TITLE
SR - Falscher Initial-Fokus (AX)

### ISSUE THREAD

**Issue by Tamara240** [DP-3T/dp3t-ux-screenflows-ch#20]
Screen: Meldungen nach Klick auf Button "Schliessen" im Screen "Gute Besserung" nach der Codeeingabe

Severity: 1 (Critical)

(1)
Wird der Initial-Fokus auf "Schliessen" gesetzt, meint der Benutzer, das Fenster müsse nun geschlossen werden. Der Benutzer merkt nicht, dass noch weitere, neue Informationen angezeigt werden.
(2)
Der Link "Anweisung zur Selbstquarantäne" enthält einen visuellen Hinweis, dass eine neue Seite geöffnet wird. Diese Information wird einem SR-Benutzer nicht ausgegeben.

![Meldungen](https://user-images.githubusercontent.com/65170302/84149530-e55ed080-aa60-11ea-86f2-a9b226e84ae1.jpg)

**Comment by bastianmorath** [comment]
Danke für das Feedback, neu erhält der User einen akustischen Hinweis, wenn die App verlassen würde. Ausserdem ist der Initialfokus angepasst.
