### ISSUE TITLE
Screenreader (AX)

### ISSUE THREAD

**Issue by Tamara240** [DP-3T/dp3t-ux-screenflows-ch#23]
Screen: Enter Covidcode

Severity: 0 (Blocker)

in screenreader modus as Tester I was difficult to:
- add numbers into code fields
- jump back or out of this screen

We highly recommend that this part must be tested from a blind person!

![IMG_5835](https://user-images.githubusercontent.com/65170302/84150164-c6147300-aa61-11ea-9f92-3b15e6c814c0.PNG)

**Comment by bastianmorath** [comment]
Thanks for the feedback, we have improved the experience of entering a code in voice over mode.
