### ISSUE TITLE
Hotline unklar wohin sie führt (UX)

### ISSUE THREAD

**Issue by Tamara240** [DP-3T/dp3t-ux-screenflows-ch#24]
Screen: Code Eingeben

Severity: 4 (Low)

Hotline sollte ersichtlich sein für User um was für eine Hotline es sich handelt.
technische Hilfe zur Codeingabe oder Medizinische Hilfe.

![covidapp code hotline](https://user-images.githubusercontent.com/65170302/84150286-f2c88a80-aa61-11ea-9432-671a3e804205.png)

**Comment by bastianmorath** [comment]
Screen existiert in dieser Form nicht mehr.
