### ISSUE TITLE
Hotline erschein nur bei Fehlereingabe (UX)

### ISSUE THREAD

**Issue by Tamara240** [DP-3T/dp3t-ux-screenflows-ch#25]
Screen: Code eingeben

Severity: 2 (Severe)

Eine Hilfestellung zur Code-Eingabe erscheint nur, wenn der Code fehlerhaft eingegeben wurde. (aus Businesssicht um die Hotline nicht zu überlasten verständlich) aus Sicht von Benützern stehen keine Informatinonen in der App direkt zur Verfügung zur Codeingabe

![covidapp code hotline (1)](https://user-images.githubusercontent.com/65170302/84150554-4e931380-aa62-11ea-96d1-6e2504f59453.png)

**Comment by mwellig** [comment]
Wir gehen davon aus (auch basierend auf UX-Tests), dass die Eingabe des Codes genügend selbsterklärend ist.
