### ISSUE TITLE
SR - Hilfe erst spät erreichbar (AX)

### ISSUE THREAD

**Issue by Tamara240** [DP-3T/dp3t-ux-screenflows-ch#26]
Screen: Code eingeben

Severity: 2 (Severe)

(1)
SR-Benutzer erfahren erst spät (nachdem sie sich durch alle Elemente und Eingabefelder durchgeswiped haben) dass es eine Hilfe gibt.

![Code eingeben 5](https://user-images.githubusercontent.com/65170302/84150691-7e421b80-aa62-11ea-8981-0d5fc3c3f496.PNG)

**Comment by bastianmorath** [comment]
Diesen Button gibt es in der aktuellen Version nicht mehr.
