### ISSUE TITLE
SR - Hauptbutton nicht erreichbar

### ISSUE THREAD

**Issue by Tamara240** [DP-3T/dp3t-ux-screenflows-ch#27]
Screen: Code eingeben

Severity: 0 (Blocker)

(1)
Nach der Code-Eingabe kann der Screenreader-Benutzer den Button "Jetzt senden" nicht erreichen. Der Eingabemodus ist immer noch aktiv und Swipen zum nächsten Element resp. dem Button ist nicht möglich.
Empfehlung: Die Eingabe und der Umgang mit der Eingabemethode sollte mit einer blinden Person welche tastächliche SR-Nutzer ist, geprüft und ausgearbeitet werden. Es gibt allenfalls Bedienungsmöglichkeiten die dem Tester nicht bekannt sind.

![code eingeben 4](https://user-images.githubusercontent.com/65170302/84162356-93be4200-aa70-11ea-8742-03beeac78830.PNG)

**Comment by bastianmorath** [comment]
Vielen Dank für das Feedback. Der VoiceOver Mode beim Code-Eingeben wurde neu überarbeitet.
