### ISSUE TITLE
Fehleranfälligkeit (AX/UX)

### ISSUE THREAD

**Issue by Tamara240** [DP-3T/dp3t-ux-screenflows-ch#28]
Screen: Code eingeben

Severity: 1 (Critical)

(1)
Wird die letzte Zahl nach einer Eingabe wieder gelöscht, bleibt der Button "Jetzt senden" trotzdem enabled.

![code eingeben 3](https://user-images.githubusercontent.com/65170302/84162534-c49e7700-aa70-11ea-817b-66c21683b58b.PNG)

**Comment by bastianmorath** [comment]
Danke, wurde behoben.
