### ISSUE TITLE
SR - keine Auszeichnung (AX)

### ISSUE THREAD

**Issue by Tamara240** [DP-3T/dp3t-ux-screenflows-ch#29]
Screen: Code eingeben

Severity: 2 (Severe)

(1)
SR liest nur vor "Code eingeben" ohne Hinweis, dass dies eine Überschrift ist. Der Benutzer kann dies somit als Handlungsanweisung verstehen und meinen, der Fokus sei bereits in einem Eingabefeld.

![code eingeben 1](https://user-images.githubusercontent.com/65170302/84162692-f3b4e880-aa70-11ea-9f75-7e890c3d1606.PNG)

**Comment by bastianmorath** [comment]
Vielen Dank für das Feedback. Der VoiceOver Mode beim Code-Eingeben wurde neu überarbeitet.
