### ISSUE TITLE
SR - Falscher Fokus (AX)

### ISSUE THREAD

**Issue by Tamara240** [DP-3T/dp3t-ux-screenflows-ch#30]
Screen: Informieren - nach klick auf Button Covid-Code Eingeben

Severity: 1 (Critical)

(1)
Der Fokus wird nach Klick auf den Button "COVID-CODE EINGEBEN" im darauf folgenden Screen direkt auf "Abbrechen" gesetzt. Der Benutzer verliert dadurch die Orientierung.

![button code 1](https://user-images.githubusercontent.com/65170302/84162940-3bd40b00-aa71-11ea-9fec-54ce16ba89f6.PNG)
![button code 2](https://user-images.githubusercontent.com/65170302/84162951-3f679200-aa71-11ea-82db-02bfc8cfa41e.PNG)

**Comment by bastianmorath** [comment]
Danke für den Hinweis, das wurde nun angepasst.
