### ISSUE TITLE
Fehlende Auszeichnung Schalter/Button (AX)

### ISSUE THREAD

**Issue by Tamara240** [DP-3T/dp3t-ux-screenflows-ch#34]
Screen: Home

Severity: 1 (Critical)

Ein Screenreader aktiviert die Kasten "Tracing Aktiv. Begegnungen werden gespeichert" und "Keine Meldungen. Es wurde keine mögliche Ansteckung gemeldet" als eigenständige Bereiche welche anklickbar sind. Die Titel "Begegnungen" und "Meldungen " werden als anklickbare Schaltflächen/Tasten ausgegeben, die jeweiligen Bereiche darunter aber nicht.

![IMG_1261 (1)](https://user-images.githubusercontent.com/65170302/84164605-016b6d80-aa73-11ea-8965-aa6b2fb86833.PNG)

**Comment by bastianmorath** [comment]
Vielen Dank für den Hinweis. Wir denken, dass es hier Sinn macht, den Titel und Untertitel im VoiceOver-Mode als eine Gruppe anstatt einzeln vorzulesen.
