### ISSUE TITLE
Kontrast (AX/UX)

### ISSUE THREAD

**Issue by Tamara240** [DP-3T/dp3t-ux-screenflows-ch#38]
Screen: Meldungen

Severity: 1 (Critical)

(1)
Kontrast grün/grün ist zu gering (2:1). Muss mind. 4.5:1 sein.

![meldungen](https://user-images.githubusercontent.com/65170302/84167767-edc20600-aa76-11ea-8af8-206bab023578.PNG)
![image2020-5-1_15-4-3](https://user-images.githubusercontent.com/65170302/84167795-f4e91400-aa76-11ea-9f72-5a11961f4e5c.png)

**Comment by maerki** [comment]
@Tamara240 Wurde das mit der Kontrast-Option aktiviert getestet?

**Comment by bastianmorath** [comment]
Die Farben wurden neu angepasst und verfügen nun über grössere Kontrastverhältnisse.
