### ISSUE TITLE
Fehlende Vorhersagbarkeit (AX/UX)

### ISSUE THREAD

**Issue by Tamara240** [DP-3T/dp3t-ux-screenflows-ch#39]
Screen: Symptome

Severity: 1 (Critical)

Der Link "Zum Coronavirus-Check" informiert einen Screenreader-Nutzer nicht darüber, dass eine Webseite (ausserhalb der App) geöffnet wird.

![IMG_1265](https://user-images.githubusercontent.com/65170302/84167937-21049500-aa77-11ea-8c57-350a24d7be62.PNG)

**Comment by bastianmorath** [comment]
Neu wird dem User ein Hinweis vorgelesen, dass der Button die App verlässt.
