### ISSUE TITLE
Fehlende Vorhersagbarkeit (AX)

### ISSUE THREAD

**Issue by Tamara240** [DP-3T/dp3t-ux-screenflows-ch#40]
Screen: Meldungen

Severity: 1 (Critical)

Der Link "So schützen wir uns" informiert einen Screenreader-Nutzer nicht darüber, dass eine Webseite (ausserhalb der App) geöffnet wird.

![IMG_1262 (1)](https://user-images.githubusercontent.com/65170302/84168140-56a97e00-aa77-11ea-95ec-4907a9e022c1.PNG)

**Comment by bastianmorath** [comment]
Vielen Dank für das Feedback. Der User wird im VoiceOver Modus neu darauf hingewiesen, wenn ein Button die App verlassen würde.
