### ISSUE TITLE
SR - Falscher Fokus nach Toggle-Button (AX)

### ISSUE THREAD

**Issue by Tamara240** [DP-3T/dp3t-ux-screenflows-ch#43]
Screen: Begegnungen - Toggle Button

Severity: 1 (Critical)

Aktiviert/Deaktiviert ein Screenreader-Nutzer den Togglebutton resp. das Tracing, wird der Fokus nach Betätigung auf den Zurück-Button gesetzt. Der Benutzer weiss aber noch nicht, ob das Tracing nun aktiviert/deaktiviert wurde und verliert zudem die Orientierung innerhalb der App. Der Fokus darf nicht ohne weiteres verändert werden.

![begegnungen 1](https://user-images.githubusercontent.com/65170302/84168834-2b735e80-aa78-11ea-9e55-24e4fdd211e3.PNG)
![begegnungen 1_2](https://user-images.githubusercontent.com/65170302/84168842-2dd5b880-aa78-11ea-86e5-8faf24cbbf32.PNG)

**Comment by bastianmorath** [comment]
Danke für die Info, der Fokus bleibt jetzt korrekterweise auf dem Control und dem User wird ein Feedback gegeben.
