### ISSUE TITLE
Kontrast: SR-Optimierung (AX/UX)

### ISSUE THREAD

**Issue by Tamara240** [DP-3T/dp3t-ux-screenflows-ch#48]
Screen: Einleitung - Was macht die App

Severity: 1 (Critical)

(1)
Kontrast 2.9:1 ist zu gering (muss mind. 4.5:1 sein)

![was macht die app (1)](https://user-images.githubusercontent.com/65170302/84169759-48f4f800-aa79-11ea-8dd1-16d5039c1881.PNG)

**Comment by maerki** [comment]
@Tamara240 Wurde das mit der Kontrast-Option aktiviert getestet?

**Comment by bastianmorath** [comment]
Die Farben wurden angepasst und verfügen nun über grössere Kontrastverhältnisse.
