### ISSUE TITLE
Kontrast: Navigation/Fehlertoleranz (AX)

### ISSUE THREAD

**Issue by Tamara240** [DP-3T/dp3t-ux-screenflows-ch#49]
Screen: Einleitung - Privacy by Design

Severity: 1 (Critical)

(1)
Kontrast 2.8:1 ist zu gering (muss mind. 4.5:1 sein)
(2)
Der Benutzer kann nicht mehr zurück navigieren
Betrifft alle Screens
"Weiter >" / "< Zurück" mit Pfeil auszeichnen
![Privacy by Design](https://user-images.githubusercontent.com/65170302/84169916-7a6dc380-aa79-11ea-8200-674e593b829e.PNG)

**Comment by maerki** [comment]
@Tamara240 Wurde das mit der Kontrast-Option aktiviert getestet?

**Comment by bastianmorath** [comment]
Die Farben wurden angepasst und verfügen nun über grössere Kontrastverhältnisse.
Ausserdem kann der User neu mit dem systemweiten 3-finger swipe im Onboarding vor und zurück navigieren.
