### ISSUE TITLE
Kontrast: SR - Auszeichnung Elemente

### ISSUE THREAD

**Issue by Tamara240** [DP-3T/dp3t-ux-screenflows-ch#50]
Screen: Einleitung - Das Prinzip

Severity: 1 (Critical)

1)
Kontrast 2.9:1 ist zu gering (muss mind. 4.5:1 sein)
(2)
SR: "Das Prinzip" ist nicht als Überschrift ausgezeichnet
Betrifft alle Screens
(3)
SR: "Dem Virus einen Schritt voraus" ist nicht als Überschrift ausgezeichnet.
Betrifft alle Screens
(4)
Kontrast für Button "Weiter" ist zu gering: 2.9:1 (muss mind. 4.5:1 sein)
![Das Prinzip](https://user-images.githubusercontent.com/65170302/84170202-b143d980-aa79-11ea-809a-12c5929e0b95.PNG)

**Comment by maerki** [comment]
@Tamara240 Wurde das mit der Kontrast-Option aktiviert getestet?

**Comment by Tamara240** [comment]
Die Kontrast-Option kennt nicht jeder und ist anscheinend auch nicht ausreichend: https://allerlay.com/de/wie-barrierefrei-ist-swisscovid-die-schweizer-tracing-app/

**Comment by bastianmorath** [comment]
Danke für die Info, die Farben wurden überarbeitet und heben sich jetzt besser voneinander ab.
