### ISSUE TITLE
Navigation/Fehlertoleranz (AX/UX)

### ISSUE THREAD

**Issue by Tamara240** [DP-3T/dp3t-ux-screenflows-ch#51]
Screens: Alle Screens der Einleitung

Severity: 3 (Medium)

Der Benutzer kann nicht mehr zurück navigieren
"Weiter >" / "< Zurück" mit Pfeil auszeichnen

**Comment by bastianmorath** [comment]
Grundsätzlich kann man mit Swipe-Gesten zurück und vor navigieren. Auf ein paar Screens ist dies aber bewusst deaktiviert, damit der User zb. den Permission-Screen nicht überspringen kann.
Ausserdem kann man neu im VoiceOver Modus mit 3-Finger Gesten vor und zurück navigieren.
