### ISSUE TITLE
SR - Fehlende Auszeichnung von Überschriften (AX)

### ISSUE THREAD

**Issue by Tamara240** [DP-3T/dp3t-ux-screenflows-ch#56]
Screen: Alle

Severity: 2 (Severe)

Überschriften sind für die Screenreader nicht ausgezeichnet. Screenreader-Benutzer haben somit keine strukturierte Benutzeroberfläche und sind auf eingene Interpretationen angewiesen.

(Die einzig ausgezeichneten Überschriften sind diejenigen im Header (z.B. "SwissCovid", "Begegnungen"). Diese allein sind jedoch nicht genug.)

**Comment by bastianmorath** [comment]
In der aktuellen Version sind alle Überschriften durch den Screenreader auswählbar.
