### ISSUE TITLE
Kontrast Schrift/Hintergrund ungenügend für Barrierefreiheit

### ISSUE THREAD

**Issue by rubenfeurer** [DP-3T/dp3t-ux-screenflows-ch#7]
Der Kontrast der Schriften zum Hintergrund ist teils ungenügend für Menschen mit Seheinschränkungen.

![Screenshot 2020-05-26 10 46 16](https://user-images.githubusercontent.com/7510803/82880588-eeb74b80-9f3e-11ea-884f-1054cc20a0c7.png)

**Comment by maerki** [comment]
Wurde das auch mit der Einstellung "erhöhter Kontrast" getestet?

**Comment by maerki** [comment]
@rubenfeurer Der Kontrast kann in den Systemeinstellungen erhöht werden.

**Comment by thematerializer** [comment]
Kontrast sollte die AA mindest Konformität von Anfang an beinhalten. Dies dem Nutzer zu übertragen erstmal Einstellungen dazu zu machen entspricht nicht einer einfachen Bentzerfreundlichkeit.

**Comment by bastianmorath** [comment]
Die Farben wurden überarbeitet und weisen neu ein besseres Kontrastverhältnis auf.
